
ph-ee-engine:
  # javaOpts:
  # minHeap: 192m
  # maxHeap: 256m
  # debugPort: 5005

  # global: 
  #   tenants: "greenbank,bluebank"
  #   DFSPIDS: "greenbank,bluebank" 

  elasticsearch:
    enabled: false

  kibana:
    enabled: false

  operations_web:
    image: docker.io/openmf/ph-ee-operations-web:dev1 



  # importer_rdbms:
    # env:
    #   - name: TENANTS_CONNECTIONS_GREENBANK_SCHEMA_SERVER
    #     value: "fredmysql"
    #   - name: TENANTS_CONNECTIONS_GORILLA_SCHEMA_SERVER
    #     value: "fred2mysql"

    # datasource:
    #   core:
    #     host: "mysql.infra.svc.cluster.local"
    #     port: 3306
    #     schema: "tenants"
    #     username: "mifos"
    #     password: "password"

  # operations_app:
  #   secret:
  #     apiversion: "v1"
  #     datasource:
  #       # username: "mifos"
  #       # password: "password"
  #       host: "mysql.infra.svc.cluster.local"
  #       # port: 3306
  #       # schema: "tenants"

  # operations:
  #   mysql:
  #     enabled: false

  camunda-platform:
    global:
      elasticsearch:
        # Elasticsearch.disableExporter if true, disables the elastic exporter in zeebe
        disableExporter: false
        host: "infra-elasticsearch.infra.svc.cluster.local"
        port: 9200
        clusterName: "fred"
      identity:
        auth:
          enabled: false

    zeebe:
      enabled: true
      logLevel: debug
      volumeClaimTemplate:
        storageClassName: "local-path"

      clusterSize: "1"
      partitionCount: "1"
      replicationFactor: "1"
      cpuThreadCount: "1"
      ioThreadCount: "1"

      resources:
        requests:
          cpu: 800m
          memory: 1200Mi
        limits:
          cpu: 960m
          memory: 1920Mi  
      affinity: {}  

    zeebe-gateway:
      enabled: false
      replicas: 1
      logLevel: debug

      resources:
        requests:
          cpu: 400m
          memory: 450Mi
        limits:
          cpu: 400m
          memory: 450Mi  
      affinity: {}

      ingress:
        enabled: true
        host: "zeebe-gateway.mifos.gazelle.test"

    operate:
      enabled: true
      replicas: 1
      logging:
        level:
          ROOT: INFO
          io.camunda.operate: DEBUG

      resources:
        requests:
          cpu: 600m
          memory: 400Mi
        limits:
          cpu: 2000m
          memory: 2Gi 
          
      affinity: {}

      ingress:
        enabled: true
        host: "zeebe-operate.mifos.gazelle.test"

    tasklist:
      enabled: false

    optimize:
      enabled: false  

    identity:
      enabled: false

    connectors:
      enabled: false

    elasticsearch:
      enabled: false
  #### end of camunda-platform


  # PH-EE Connector Mojaloop
  # Note 'fred' and 'FRED' are development hooks as we continue to work on end to end integration flows.
  ph_ee_connector_mojaloop:
    enabled: false
    # the following 2 entries used only for dev/test of mojaloop connector 
    # image: mojaloop-connector:gazelle
    imagePullPolicy: "Never"
    image: mojaloop:gazelle1 
    ingress:
      enabled: true
      className: nginx
    switch:
      quotes:
        host: ""
        service: ""
      als:
        host: "fspiop.mifos.gazelle.test"
        service: "fspiop.mifos.gazelle.test"
      transfers:
        host: "fspiop.mifos.gazelle.test"
        service: ""
      transactions:
        host: "fspiop.mifos.gazelle.test"
        service: ""
      oracle:
        host: "fspiop.mifos.gazelle.test"
    deployment:
      extraEnvs:
        - name: parties_0_domain
          value: "mojaloop.mifos.gazelle.test"
        - name: parties_1_domain
          value: "mojaloop.fred.io"
        - name: parties_2_domain
          value: "mojaloop.fred.io"
        - name: parties_3_domain
          value: "mojaloop.fred.io"
        - name: parties_0_tenantId
          value: "greenbank"
        - name: parties_1_tenantId
          value: "bluebank"
        - name: parties_0_fspId
          value: "payerfsp"
        - name: parties_1_fspId
          value: "payeefsp"
        - name: parties_2_fspId
          value: "payeefsp2"
        - name: parties_3_fspId
          value: "payeefsp3"

  ph_ee_connector_ams_mifos:
    enabled: true
    SPRING_PROFILES_ACTIVE: "fin12,bb"
    #image: docker.io/openmf/ph-ee-connector-ams-mifos:v1.7.0
    image: docker.io/devarsh10/ph-ee-connector-ams-mifos:latest

  post_installation_job:
    enabled: false

  integration_test:
    enableAMSTest: false
    enableGOVTest: false
    enableGazelleTest: true 
    imagePullPolicy: IfNotPresent
    image: docker.io/openmf/ph-ee-integration-test:v1.6.2-gazelle
    imagePullPolicy: IfNotPresent
    testTags: "@gov and not @ext"
    memoryRequest: "500k"
    testResultsOutputDir: "/tmp"

# deployment:
#   extraEnvs:
#     - name: TOM_OPTS_2
#       value: "this is FRED2 one of toms deployment options"

  operations_app:
    enabled: true
    #image: docker.io/openmf/ph-ee-operations-app:v1.20.0
    deployment:
      extraEnvs:
        - name: "TOMS_OPTS"
          value: "of-no-value"
        - name: "TOMS_OPTS-3"
          value: "of-no-value"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms128m -Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:9876"

  connector_bulk:
    tenants: "greenbank,bluebank"
    operations_app:
      #contactpoint: "http://ph-ee-operations-app:5000"
      contactpoint: "http://ph-ee-operations-app:80"
      endpoints:
        batch_transaction: "/api/v1/batch/transactions"
    spec:
      template:
        containers:
          env:
            - name: "BP_JAVA_OPTS"
              value: ""
            - name: "BP_JAVA_OPTS-1"
              value: "fred5"
            - name: "BP_JAVA_OPTS-2"
              value: "fred6"  
            # - name: "TOMS_OPTS"
            #   value: "of-no-value"
    deployment:
      extraEnvs:
        - name: JAVA_TOOL_OPTIONS
          value: |
            -Xms128m
            -Xmx256m
            -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=localhost:5010


# tls:
# - hosts:
#   - channel.mifos.gazelle.test
#   - channel-gsma.mifos.gazelle.test
#   secretName: sandbox-secret

  channel:
    tenantPrimary:
      clientId: "mifos"
      clientSecret: "password"
      tenant: "greenbank"
    tenantSecondary:
      clientId: "mifos"
      clientSecret: "password"
      tenant: "bluebank"
    # application:
    #   config:
    #     server:
    #       ssl:
    #         enabled: false
    LOGGING_LEVEL_ROOT: "DEBUG"
    deployment:
      extraEnvs:
        - name: "SERVER_SSL_ENABLED"
          value: "false"
        - name: "SERVER_PORT"
          value: "8080"

    ingress:
      enabled: true
      className: nginx
      pathType: Prefix
      tls:
      - hosts:
        - channel.mifos.gazelle.test
        # - channel-gsma.mifos.gazelle.test
        secretName: sandbox-secret
      hosts:
        - host: channel.mifos.gazelle.test          
          paths: 
          - path: /
            backend:
              service:
                name: ph-ee-connector-channel
                port:
                  number: 82
        # - host: channel-gsma.mifos.gazelle.test          
        #   paths:          
        #   - path: /
        #     backend:
        #       service:
        #         name: ph-ee-connector-channel-gsma
        #         port:
        #           number: 82

  minio:
    ingress:
      hosts:
        - minio.mifos.gazelle.test

    
    consoleIngress:
      enabled: true 
      ingressClassName: nginx 
      labels: {}
      annotations: {}
      path: /
      hosts:
        - minio-console.mifos.gazelle.test


  ph-ee-connector:
    enabled: true

