global:
    # Elasticsearch configuration which is shared between the sub charts
  elasticsearch:
    # Elasticsearch.disableExporter if true, disables the elastic exporter in zeebe
    disableExporter: false
    # Elasticsearch.url can be used to configure the URL to access elasticsearch, if not set services fallback to host and port configuration
    url:
    # Elasticsearch.protocol defines the elasticsearch access protocol, by default HTTP.
    protocol: http
    # Elasticsearch.host defines the elasticsearch host, ideally the service name inside the namespace
    host: "infra-elasticsearch.infra.svc.cluster.local"
    # Elasticsearch.port defines the elasticsearch port, under which elasticsearch can be accessed
    port: 9200
    # Elasticsearch.clusterName defines the cluster name which is used by Elasticsearch
    clusterName: "default"

  identity:
    auth:
      enabled: false

zeebe:
  enabled: true
  logLevel: debug
  volumeClaimTemplate:
    storageClassName: "local-path"

  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"

  # CpuThreadCount defines how many threads can be used for the processing on each broker pod
  cpuThreadCount: "1"
  # IoThreadCount defines how many threads can be used for the exporting on each broker pod
  ioThreadCount: "1"

  resources:
    requests:
      cpu: 800m
      memory: 1200Mi
    limits:
      cpu: 960m
      memory: 1920Mi  
  affinity: {}  

zeebe-gateway:
  enabled: true
  replicas: 1
  logLevel: info

  resources:
    requests:
      cpu: 400m
      memory: 450Mi
    limits:
      cpu: 400m
      memory: 450Mi  
  affinity: {}

  ingress:
    enabled: true
    host: "zeebe-gateway.mifos.gazelle.test"

operate:
  enabled: true
  replicas: 1
  logging:
    level:
      ROOT: INFO
      io.camunda.operate: DEBUG

  resources:
    requests:
      cpu: 600m
      memory: 400Mi
    limits:
      cpu: 2000m
      memory: 2Gi 
      
  affinity: {}

  ingress:
    enabled: true
    host: "zeebe-operate.mifos.gazelle.test"

tasklist:
  enabled: false

optimize:
  enabled: false  

identity:
  enabled: false

connectors:
  enabled: false

elasticsearch:
  enabled: false
